declare namespace Express {
	/*
		NOTE: The naming-convention rule has been disabled for this line because
		Request is part of @types/express and can't be renamed to
		iRequest
	 */
	// eslint-disable-next-line @typescript-eslint/naming-convention
	export interface Request {
		/**
		 * Unique request ID generated by the middleware.
		 */
		uniqueRequestId: string;

		/**
		 * OIDC context object added to each request by the middleware.
		 */
		oidcContext: {
			email: string;
		} | null;
	}
}
